version: '3.0'
services:

  rasa-flask:
    image: rasa-chatbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rasa-chat-app
    volumes: 
      - .:/rasa_app
    ports:
      - 5000:5000
    command: python3 app.py

  rasa-server:
    image: rasa/rasa:3.2.6-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run -m models --enable-api --cors "*"
  app:
    image: <image:tag>
    expose: 5055:5005